# Generated by Django 5.1.1 on 2024-10-01 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=80)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
