# Generated by Django 5.1.1 on 2024-10-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management', '0004_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee_id', 'date')},
        ),
    ]
